// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginREQ struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginREQ) Reset()         { *m = LoginREQ{} }
func (m *LoginREQ) String() string { return proto.CompactTextString(m) }
func (*LoginREQ) ProtoMessage()    {}
func (*LoginREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginREQ.Unmarshal(m, b)
}
func (m *LoginREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginREQ.Marshal(b, m, deterministic)
}
func (m *LoginREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginREQ.Merge(m, src)
}
func (m *LoginREQ) XXX_Size() int {
	return xxx_messageInfo_LoginREQ.Size(m)
}
func (m *LoginREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginREQ.DiscardUnknown(m)
}

var xxx_messageInfo_LoginREQ proto.InternalMessageInfo

func (m *LoginREQ) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginREQ) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginACK struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginACK) Reset()         { *m = LoginACK{} }
func (m *LoginACK) String() string { return proto.CompactTextString(m) }
func (*LoginACK) ProtoMessage()    {}
func (*LoginACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginACK.Unmarshal(m, b)
}
func (m *LoginACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginACK.Marshal(b, m, deterministic)
}
func (m *LoginACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginACK.Merge(m, src)
}
func (m *LoginACK) XXX_Size() int {
	return xxx_messageInfo_LoginACK.Size(m)
}
func (m *LoginACK) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginACK.DiscardUnknown(m)
}

var xxx_messageInfo_LoginACK proto.InternalMessageInfo

func (m *LoginACK) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoREQ struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoREQ) Reset()         { *m = UserInfoREQ{} }
func (m *UserInfoREQ) String() string { return proto.CompactTextString(m) }
func (*UserInfoREQ) ProtoMessage()    {}
func (*UserInfoREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserInfoREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoREQ.Unmarshal(m, b)
}
func (m *UserInfoREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoREQ.Marshal(b, m, deterministic)
}
func (m *UserInfoREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoREQ.Merge(m, src)
}
func (m *UserInfoREQ) XXX_Size() int {
	return xxx_messageInfo_UserInfoREQ.Size(m)
}
func (m *UserInfoREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoREQ.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoREQ proto.InternalMessageInfo

func (m *UserInfoREQ) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoACK struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoACK) Reset()         { *m = UserInfoACK{} }
func (m *UserInfoACK) String() string { return proto.CompactTextString(m) }
func (*UserInfoACK) ProtoMessage()    {}
func (*UserInfoACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfoACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoACK.Unmarshal(m, b)
}
func (m *UserInfoACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoACK.Marshal(b, m, deterministic)
}
func (m *UserInfoACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoACK.Merge(m, src)
}
func (m *UserInfoACK) XXX_Size() int {
	return xxx_messageInfo_UserInfoACK.Size(m)
}
func (m *UserInfoACK) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoACK.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoACK proto.InternalMessageInfo

func (m *UserInfoACK) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginREQ)(nil), "pb.LoginREQ")
	proto.RegisterType((*LoginACK)(nil), "pb.LoginACK")
	proto.RegisterType((*UserInfoREQ)(nil), "pb.UserInfoREQ")
	proto.RegisterType((*UserInfoACK)(nil), "pb.UserInfoACK")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72, 0xe0, 0xe2, 0xf0, 0xc9,
	0x4f, 0xcf, 0xcc, 0x0b, 0x72, 0x0d, 0x14, 0x92, 0xe0, 0x62, 0x77, 0x4c, 0x4e, 0xce, 0x2f, 0xcd,
	0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0xa4, 0xb8, 0x38, 0x02, 0x12,
	0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc0, 0x52, 0x70, 0xbe, 0x92, 0x02, 0xd4, 0x04,
	0x47, 0x67, 0x6f, 0x21, 0x11, 0x2e, 0xd6, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0xa8, 0x7e, 0x08, 0x47,
	0x49, 0x99, 0x8b, 0x3b, 0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x2f, 0x2d, 0x1f, 0x64, 0x0d, 0x76, 0x45,
	0xea, 0x08, 0x45, 0x20, 0x93, 0x70, 0xba, 0x25, 0x89, 0x0d, 0xec, 0x78, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x68, 0xe6, 0x37, 0x63, 0xca, 0x00, 0x00, 0x00,
}
